pipeline:
  - stage: disparity/sgm
    params:
      num_disparities: 64
      block_size: 7

  - stage: depth/depth_from_disp
    params:
      focal_length: 374.0
      baseline: 0.1

  - stage: postproc/bilateral
    params:
      d: 9
      sigmaColor: 75
      sigmaSpace: 75

  - stage: pointcloud/from_depth
  - stage: mesh/poisson
    params: { depth: 8 }
  - stage: finalize/clean
    params: { target_triangles: 50000 }